GET http://localhost:3000/api/meme

### 

GET http://localhost:3000/api/local

###

POST http://localhost:3000/api/local
Content-Type: application/json

    {
        "name": "MemeFour",
        "url": "https://i.imgflip.com/jrj7.jpg"
    }


###