GET http://localhost:3000/api/meme

### 

GET http://localhost:3000/api/local

###

POST http://localhost:3000/api/local
Content-Type: application/json

    {
        "name": "MemeFour"       
    }


###